# Generated by Django 4.0.1 on 2022-04-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_name', models.CharField(max_length=200, unique=True, verbose_name='نام اگهی ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اگهی')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='photos/ads', verbose_name='تصویر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('is_available', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='AdsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='photos/ads', verbose_name='تصویر')),
                ('ads', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ads.ads', verbose_name='اگهی')),
            ],
            options={
                'verbose_name': 'گالری تصاویر اگهی',
                'verbose_name_plural': 'گالری تصاویر اگهی',
            },
        ),
    ]
