# Generated by Django 4.0.1 on 2022-02-28 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=120, verbose_name='نام')),
                ('last_name', models.CharField(max_length=120, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=120, unique=True, verbose_name='شماره همراه')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='اخرین ورود')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'حساب های کاربران',
                'verbose_name_plural': 'حساب های کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس اول ')),
                ('profile_picture', models.ImageField(blank=True, default='photos/userprofile/user.png', null=True, upload_to='photos/userprofile', verbose_name='تصویر کاربر')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='کوچه')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='کشور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربران',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
