# Generated by Django 4.0.1 on 2022-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=120, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
