# Generated by Django 4.0.1 on 2022-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/slider', verbose_name='اسلایدر اول')),
                ('image2', models.ImageField(upload_to='photos/slider', verbose_name='اسلایدر دوم')),
                ('image3', models.ImageField(upload_to='photos/slider', verbose_name='اسلایدر سوم')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
