# Generated by Django 4.0.1 on 2022-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/slider', verbose_name='اسلایدر '),
            preserve_default=False,
        ),
    ]
