# Generated by Django 4.0.1 on 2022-02-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='شماره سفارش')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='ادرس ')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('state', models.CharField(max_length=50, verbose_name='کوچه')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('order_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت')),
                ('order_total', models.FloatField(verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('قبول', 'قبول'), ('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده')], default='New', max_length=10, verbose_name='وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='ادرس ip')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='وضعیت خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='آیدی پرداخت')),
                ('payment_method', models.CharField(max_length=100, verbose_name='روش پرداخت')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='قیمت')),
                ('status', models.CharField(max_length=100, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='موجودی')),
                ('product_price', models.FloatField(verbose_name='قیمت محصول')),
                ('ordered', models.BooleanField(default=False, verbose_name='وضعیت سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='پرداخت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variations', models.ManyToManyField(blank=True, to='store.Variation', verbose_name='ایتم های انتخاب شده')),
            ],
            options={
                'verbose_name': 'سفارش محصول',
                'verbose_name_plural': 'سفارش محصولات',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='خرید'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
