# Generated by Django 4.0.1 on 2022-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='ایمیل'),
        ),
    ]
