# Generated by Django 4.0.1 on 2022-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=50, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
